// <auto-generated />
using System;
using FeeQuery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeeQuery.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208083355_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FeeQuery.Shared.Models.AlertHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("AlertRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CloudAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExceedPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThresholdAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("CloudAccountId");

                    b.HasIndex("Status");

                    b.HasIndex("TriggeredAt");

                    b.ToTable("AlertHistories");
                });

            modelBuilder.Entity("FeeQuery.Shared.Models.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CloudAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationChannels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationTargets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CloudAccountId");

                    b.HasIndex("IsEnabled");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("FeeQuery.Shared.Models.BillingRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CloudAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Usage")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageUnit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillingDate");

                    b.HasIndex("CloudAccountId");

                    b.HasIndex("ProviderCode");

                    b.HasIndex("CloudAccountId", "BillingDate");

                    b.ToTable("BillingRecords");
                });

            modelBuilder.Entity("FeeQuery.Shared.Models.CloudAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedCredentials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("ProviderCode");

                    b.ToTable("CloudAccounts");
                });

            modelBuilder.Entity("FeeQuery.Shared.Models.AlertHistory", b =>
                {
                    b.HasOne("FeeQuery.Shared.Models.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeeQuery.Shared.Models.CloudAccount", "CloudAccount")
                        .WithMany()
                        .HasForeignKey("CloudAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");

                    b.Navigation("CloudAccount");
                });

            modelBuilder.Entity("FeeQuery.Shared.Models.AlertRule", b =>
                {
                    b.HasOne("FeeQuery.Shared.Models.CloudAccount", "CloudAccount")
                        .WithMany()
                        .HasForeignKey("CloudAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CloudAccount");
                });

            modelBuilder.Entity("FeeQuery.Shared.Models.BillingRecord", b =>
                {
                    b.HasOne("FeeQuery.Shared.Models.CloudAccount", "CloudAccount")
                        .WithMany()
                        .HasForeignKey("CloudAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CloudAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
